package pl.droidsonroids.gradle.jacoco.testkit

import org.gradle.api.tasks.Input
import org.gradle.api.tasks.WriteProperties
import pl.droidsonroids.gradle.jacoco.testkit.Configurations.jacocoRuntime
import java.io.File

open class GenerateJaCoCoTestKitProperties : WriteProperties() {
    @Input
    var destinationFile = "${project.buildDir}/jacoco/test.exec"

    init {
        group = "verification"
        description = "Generates gradle.properties with JaCoCo java agent for TestKit"
        outputFile = File(project.testKitDir(), "testkit-gradle.properties")
        comment = "Generated by pl.droidsonroids.jacoco.testkit"

        super.property("org.gradle.jvmargs", {
            val jacocoRuntimePath = project.configurations.getByName(jacocoRuntime).asPath
            val destinationAsFile = project.file(destinationFile)
            "\"-javaagent:$jacocoRuntimePath=destfile=$destinationAsFile\""
        })
    }
}
