package pl.droidsonroids.gradle.jacoco.testkit

import org.gradle.api.DefaultTask
import org.gradle.api.artifacts.Configuration
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import pl.droidsonroids.gradle.jacoco.testkit.Configurations.jacocoRuntime
import java.io.File
import java.util.Properties

open class GenerateJaCoCoTestKitProperties : DefaultTask() {
    @OutputFile
    val outputFile: File = File(project.testKitDir(), "testkit-gradle.properties")
    @Input
    val jacocoRuntimeConfiguration: Configuration = project.configurations.getByName(jacocoRuntime)
    @Input
    var destinationFile = "${project.buildDir}/jacoco/test.exec"

    init {
        group = "verification"
        description = "Generates gradle.properties with JaCoCo java agent for TestKit"
    }

    @TaskAction
    fun createJacocoProperties() {
        outputFile.ensureParentExists()
        val jacocoRuntimePath = jacocoRuntimeConfiguration.asPath
        val destinationAsFile = project.file(destinationFile)

        val properties = Properties()
        properties.setProperty("org.gradle.jvmargs", "\"-javaagent:$jacocoRuntimePath=destfile=$destinationAsFile\"")
        outputFile.outputStream().use { outputStream ->
            properties.store(outputStream, "Generated by pl.droidsonroids.jacoco.testkit")
        }
    }
}
